Feature/implement sonarcube (#11)
* Added the sonar scanner stage in the jenkins file

* Added code in the jenkinsfile to run the script. Changed the CRLF to LF for gradlew.

* Fixed the error of unexpected character in the jenkinsfile

* Fixed error in jenkinsfile

* Fixed error in the jenkinsfile

* Fixed error

* Fixed errors

* Changed agent for sonarscan

* Adding .s2i/bin folder and modifying .gitignore files to ensure it gets updated

* Trying out adding the Sonar jenkins file as it is

* Trying out a new configuration by putting podtemplate code outside of stages

* Trying out a new configuration by putting podtemplate outside of pipeline

* Reverting all jenkins file changes

* Updated build.yaml to add sonar details and updated assemble to use them

* Added a project guid to csproj because sonar requires it.

* Install Java when trying to run Sonar

* Trying sudo to install Java

* Adding builds for sonar

* Reverting jenkins file name change

* Putting up sonarscan stage for testing and removing pipeline-cli variables for now

* Remove unused parameters

* Removing redundant character in path

* Hardcoding types in yaml file

* Changing kind from DockerImage to ImageStreamTag

* Reverting to dotnet 2.1

* Reverting back and testing the changes

* Resolved bug in sonar-build and sonar

* Removing the basic sonar build

* Adding a image stream

* Hardcode the image name and the image tag in the sonar

* add changes to sonar

* add indentation

* changed image name

* deleted sonar runner

* Added the post section in the SonarScan stage

* Added commentOnPR in the post section under sonarscan stage

* adding commentOnPR under always section

* Added a reference to GitHubHelper

* Resolving a minor bug with ;

* Added missing quotes

* adding stuff within the script

* Trying to see if we can create a new project in sonar via commandline

* Added pwd to the sonar scanner end step

* Updating sonar.js to accept project and jenkins file to notify stages and add comments to PR

* Reverting jenkins file name

* sucess to success => minor name change

* Another minor error => reverting = to -

* Rebuilding the base image

* Added change id to image name

* Making user as root to avoid permissions issue

* Updating build image to make directories accessible to 10001 user

* Resolved a few bugs and reverted to adding SONAR_TOKEN

* Resolving a small error with SOURCE_REPO_REF variable

* Fixing error deployment error

* Fixing groovy error

* Defining inside the create deployment function

* Commenting out the createDeploymentStatus function

* Omitting createdeploymentstatus function

* testing deployment again

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,8 +1,12 @@
 #!/bin/bash
 
 # S2I Assemble Script
-# For the BC Dev Exchange Website project
+
 # This script is based on the S2I assemble script for dotnet 2, with the following extra features:
+#
+# 1. A Sonarqube scan can be done on the source
+# 2. Dotnet tests can be done
+# 3. Or a regular build for production of an application image can be done
 
 set -e
 
@@ -131,45 +135,40 @@ echo "---> Restoring application dependencies..."
 dotnet restore "$DOTNET_STARTUP_PROJECT" $RESTORE_OPTIONS
 
 if [ -n "$SONAR_TOKEN" ]; then
-	echo "---> Running SonarQube Scan..."
+	echo "---> Running SonarQube Scan... with password $SONAR_PWD"
   	dotnet tool install --global dotnet-sonarscanner
-  	dotnet sonarscanner begin /d:sonar.login=$SONAR_TOKEN /k:"$SONAR_PROJECT" /d:sonar.host.url=$SONAR_URL
+  	dotnet sonarscanner begin /d:sonar.login="$SONAR_TOKEN" /d:sonar.password="$SONAR_PWD" /k:"$SONAR_PROJECT" /d:sonar.host.url=$SONAR_URL
   	dotnet build "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION"
-  	dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
-elif [ -n "$SNYK_TOKEN" ]; then
-	# Run the snyk scan.  Note SNYK_TOKEN is automatically used by the snyk scanner for authentication.
-	echo "---> Running Snyk Scan..."
-	snyk test --file="$DOTNET_STARTUP_PROJECT"
-elif [ -n "$DOTNET_TEST" ]; then
-	dotnet test "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION"
+  	dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" /d:sonar.password="$SONAR_PWD"
+
 else
-	# build and publish the application for production usage
-	echo "---> Publishing application..."
-	dotnet publish /m:1 "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION" \
-		 --self-contained false /p:AssemblyVersion=$VERSION_PREFIX$BUILDNUMBER /p:FileVersion=$VERSION_PREFIX$BUILDNUMBER /p:PublishWithAspNetCoreTargetManifest=$DOTNET_ASPNET_STORE -o "$DOTNET_APP_PATH"
+  # build and publish the application for production usage
+  echo "---> Publishing application..."
+  dotnet publish /m:1 "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION" \
+      --self-contained false /p:AssemblyVersion=$VERSION_PREFIX$BUILDNUMBER /p:FileVersion=$VERSION_PREFIX$BUILDNUMBER /p:PublishWithAspNetCoreTargetManifest=$DOTNET_ASPNET_STORE -o "$DOTNET_APP_PATH"
 
-	# check if the assembly used by the script exists
-	if [ ! -f "$DOTNET_APP_PATH/${APP_DLL_NAME}" ]; then
-	  echo "error: Build output does not contain entrypoint assembly: ${APP_DLL_NAME}"
-	  exit 1
-	fi
+  # check if the assembly used by the script exists
+  if [ ! -f "$DOTNET_APP_PATH/${APP_DLL_NAME}" ]; then
+    echo "error: Build output does not contain entrypoint assembly: ${APP_DLL_NAME}"
+    exit 1
+  fi
 
-	# Create run script in publish folder
-	cat << EOF >"$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
+  # Create run script in publish folder
+  cat << EOF >"$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
 #!/bin/bash
 exec dotnet ${APP_DLL_NAME} \$@
 EOF
-	chmod +x "$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
+  chmod +x "$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
 
-	if [ "$DOTNET_PACK" == "true" ]; then
-	  echo "---> Packing application..."
-	  fix-permissions $DOTNET_APP_PATH
-	  tar -czf /opt/app-root/app.tar.gz -C $DOTNET_APP_PATH .
-	fi
+  if [ "$DOTNET_PACK" == "true" ]; then
+    echo "---> Packing application..."
+    fix-permissions $DOTNET_APP_PATH
+    tar -czf /opt/app-root/app.tar.gz -C $DOTNET_APP_PATH .
+  fi
 
-	# cleanup NuGet artifacts
-	rm -rf ~/{.local,.nuget}
+  # cleanup NuGet artifacts
+  rm -rf ~/{.local,.nuget}
 
-	# fix permissions
-	fix-permissions /opt/app-root
-fi
+  # fix permissions
+  fix-permissions /opt/app-root
+  fi
