Updated build.yaml to add sonar details and updated assemble to use them

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -139,22 +139,20 @@ if [ -n "$SONAR_TOKEN" ]; then
   	dotnet sonarscanner begin /d:sonar.login=$SONAR_TOKEN /k:"$SONAR_PROJECT" /d:sonar.host.url=$SONAR_URL
   	dotnet build "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION"
   	dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
-elif [ -n "$DOTNET_TEST" ]; then
-	dotnet test "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION"
-else
-	# build and publish the application for production usage
-	echo "---> Publishing application..."
-	dotnet publish /m:1 "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION" \
-		 --self-contained false /p:AssemblyVersion=$VERSION_PREFIX$BUILDNUMBER /p:FileVersion=$VERSION_PREFIX$BUILDNUMBER /p:PublishWithAspNetCoreTargetManifest=$DOTNET_ASPNET_STORE -o "$DOTNET_APP_PATH"
+fi
+# build and publish the application for production usage
+echo "---> Publishing application..."
+dotnet publish /m:1 "$DOTNET_STARTUP_PROJECT" -f "$DOTNET_FRAMEWORK" -c "$DOTNET_CONFIGURATION" \
+    --self-contained false /p:AssemblyVersion=$VERSION_PREFIX$BUILDNUMBER /p:FileVersion=$VERSION_PREFIX$BUILDNUMBER /p:PublishWithAspNetCoreTargetManifest=$DOTNET_ASPNET_STORE -o "$DOTNET_APP_PATH"
 
-	# check if the assembly used by the script exists
-	if [ ! -f "$DOTNET_APP_PATH/${APP_DLL_NAME}" ]; then
-	  echo "error: Build output does not contain entrypoint assembly: ${APP_DLL_NAME}"
-	  exit 1
-	fi
+# check if the assembly used by the script exists
+if [ ! -f "$DOTNET_APP_PATH/${APP_DLL_NAME}" ]; then
+  echo "error: Build output does not contain entrypoint assembly: ${APP_DLL_NAME}"
+  exit 1
+fi
 
-	# Create run script in publish folder
-	cat << EOF >"$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
+# Create run script in publish folder
+cat << EOF >"$DOTNET_APP_PATH/$DOTNET_DEFAULT_CMD"
 #!/bin/bash
 exec dotnet ${APP_DLL_NAME} \$@
 EOF
@@ -171,4 +169,4 @@ EOF
 
 	# fix permissions
 	fix-permissions /opt/app-root
-fi
+
